// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieuhuyregqzxfytnccrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldWh1eXJlZ3F6eGZ5dG5jY3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjcxNjYsImV4cCI6MjA2Mjc0MzE2Nn0.PdkpVjARrU-r_tJzx5RqaA36TnGL7d2TeqGKk7CKC0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);